name: Deploy to PyPI  # This is the workflow name

on:
  push:
    branches:
      - main  # Trigger the workflow when changes are pushed to the main branch
  release:
    types: [created]  # Trigger the workflow when a new release is created

jobs:
  build:
    runs-on: ubuntu-latest  # The type of runner that the job will run on

    steps:
    - uses: actions/checkout@v2  # Checks-out your repository under $GITHUB_WORKSPACE

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run tests
      run: |
        pytest

    - name: Build and publish to PyPI
      if: github.event_name == 'release' && github.event.action == 'created'
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/* --verbose --skip-existing
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}

